[package]
name = "catfact-networking"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
catfact-core = { path = "../core" }
reqwest = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
